alias u := update
alias r := release
alias t := test
alias b := build
alias f := fmt
alias d := dev

export RUSTFLAGS := '-C target-cpu=native'

dev:
    cargo run

update:
    cargo update

test:
    cd {{invocation_directory()}}; cargo +nightly nextest run --all-features

testt:
    cargo +nightly nextest run --all-features --workspace

fmt:
    cd {{invocation_directory()}}; cargo +nightly fmt ; cargo +nightly clippy --examples --tests --benches --all-features --fix --allow-dirty  --allow-staged

fmtt:
    cargo +nightly fmt --all ; cargo +nightly clippy --workspace --lib --examples --tests --benches --all-features --fix --allow-dirty  --allow-staged

clippy:
    cargo clippy --fix --allow-dirty

release:
    cargo build --workspace --release

release-linux:
    cargo build --target x86_64-unknown-linux-musl --release

build:
    cargo build

pre: fmt test
