alias u := update
alias r := release
alias t := test
alias b := build
alias f := fmt
alias d := dev

dev:
    RUST_LOG=INFO cargo run

update:
    cargo update

test:
    cargo test -- --nocapture

fmt: fmt-ts
    cargo fmt --all;

css-webapp:
    bunx @tailwindcss/cli -i './styles/global.css' -o './dist/output.css' --minify --watch

css-prototype:
    bunx tailwindcss -c './tailwind.config.js' -i './styles/global.css' -o './dist/prototype_output.css' --minify --watch

compile-js-webapp:
    npx swc -d dist templates --watch

clippy:
    cargo clippy --fix --allow-dirty

fmt-ts:
    bunx biome format ./templates/ --write

test-e2e:
    '.\node_modules\.bin\playwright' test './e2etests'

release:
    cargo build --release

# `&`&
release-linux:
    wsl ~/.cargo/bin/cargo build --release

build:
    cargo build --bin web-api

pre: fmt test